/**
 * Skills System Types
 *
 * Skills are higher-level abstractions above Tools that package:
 * - Multi-tool workflows
 * - Specialized prompts for domain-specific reasoning
 * - Custom result formats
 * - Model tier selection
 */

import { ToolContext } from '@/types/agent';
import { ModelTier } from '@/config/models';

/**
 * Input for skill execution
 */
export interface SkillInput {
  /** The user's query or request */
  query: string;
  /** Additional context or parameters */
  params?: Record<string, unknown>;
  /** Files attached to the request */
  files?: Array<{
    name: string;
    type: string;
    content: string | Buffer;
  }>;
}

/**
 * Output from skill execution
 */
export interface SkillOutput {
  success: boolean;
  /** Main result data */
  data?: unknown;
  /** Human-readable summary */
  summary?: string;
  /** Structured sections for display */
  sections?: SkillSection[];
  /** Figures/images extracted or generated */
  figures?: SkillFigure[];
  /** Error message if failed */
  error?: string;
  /** Execution metadata */
  metadata?: {
    tokensUsed?: number;
    costEstimate?: number;
    toolsInvoked?: string[];
    durationMs?: number;
    /** Paper title (from arXiv API or PDF metadata) */
    title?: string;
    /** arXiv ID if applicable */
    arxivId?: string;
    /** Files explored (for repo analysis) */
    filesExplored?: number;
    /** Project type detected (for repo analysis) */
    projectType?: string;
  };
}

/**
 * A section of skill output for structured display
 */
export interface SkillSection {
  title: string;
  content: string;
  type: 'text' | 'list' | 'code' | 'table';
}

/**
 * A figure extracted or generated by a skill
 */
export interface SkillFigure {
  id: string;
  /** Page number if from PDF */
  page?: number;
  /** Base64 encoded image */
  imageBase64: string;
  /** Figure dimensions */
  dimensions: { width: number; height: number };
  /** Caption or description */
  caption?: string;
  /** Importance score (0-100) */
  importance?: number;
  /** Why this figure is important */
  importanceReason?: string;
  /** Figure type classification */
  type?: 'chart' | 'diagram' | 'graph' | 'table' | 'illustration' | 'photo' | 'unknown';
}

/**
 * Skill definition interface
 */
export interface Skill {
  /** Unique skill identifier */
  id: string;
  /** Human-readable name */
  name: string;
  /** Description of what the skill does */
  description: string;
  /** Tools required by this skill */
  requiredTools: string[];
  /** Preferred model tier for this skill */
  modelTier?: ModelTier;
  /** Execute the skill */
  execute(input: SkillInput, context: ToolContext): Promise<SkillOutput>;
}

/**
 * Extended context for skills with additional data
 */
export interface SkillContext extends ToolContext {
  /** PDF buffer if loaded (ArrayBuffer for compatibility with PdfToolContext) */
  pdfBuffer?: ArrayBuffer;
  /** Extracted text content */
  textContent?: string;
  /** Extracted figures */
  figures?: SkillFigure[];
  /** Paper metadata if available */
  paperMetadata?: {
    title?: string;
    authors?: string[];
    abstract?: string;
  };
}
